# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da3c188586e51aeb988a7387de863308c5eca91fe06277ed3c7707052c2c875424e124683334b81741b347c8c913dc88ae8cf3bf4520afce6a6cae3631ccc203

test:
  secret_key_base: 993581eb228e10f1903ab3a6c7535a8c4bc70e63a9e24771e9de2aa3331cd45b5e59d9f8f0c37a55198d97061ae4339109854dbc445fc8e38e9dcca55a74faf3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
